environment:
  home: C:\projects

version: '{branch}-{build}'

os: Visual Studio 2015

build_script:
  - python dtu_tabu.py -m 5 -n 5 --size_tabu 10 --global_loops 1000 --num_candidates 4 application.graphml

configuration:
  - Release
